# Generated by Django 5.2.6 on 2025-09-28 14:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        help_text="TMDb genre ID", primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "genres",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MovieCache",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        help_text="TMDb movie ID", primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("overview", models.TextField(blank=True)),
                (
                    "poster_path",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "backdrop_path",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("release_date", models.DateField(blank=True, null=True)),
                (
                    "vote_average",
                    models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
                ),
                ("vote_count", models.IntegerField(default=0)),
                ("genres", models.JSONField(blank=True, default=list)),
                (
                    "runtime",
                    models.IntegerField(
                        blank=True, help_text="Runtime in minutes", null=True
                    ),
                ),
                ("original_language", models.CharField(blank=True, max_length=10)),
                (
                    "popularity",
                    models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
                ),
                ("cached_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "movies_cache",
                "indexes": [
                    models.Index(fields=["title"], name="movies_cach_title_484b02_idx"),
                    models.Index(
                        fields=["-release_date"], name="movies_cach_release_478f2c_idx"
                    ),
                    models.Index(
                        fields=["-vote_average"], name="movies_cach_vote_av_93d819_idx"
                    ),
                    models.Index(
                        fields=["-popularity"], name="movies_cach_popular_df3889_idx"
                    ),
                    models.Index(
                        fields=["-cached_at"], name="movies_cach_cached__f45155_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="MovieGenre",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "genre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movie_genres",
                        to="movies.genre",
                    ),
                ),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movie_genres",
                        to="movies.moviecache",
                    ),
                ),
            ],
            options={
                "db_table": "movie_genres",
                "indexes": [
                    models.Index(
                        fields=["movie"], name="movie_genre_movie_i_011b21_idx"
                    ),
                    models.Index(
                        fields=["genre"], name="movie_genre_genre_i_d5ee0c_idx"
                    ),
                ],
                "unique_together": {("movie", "genre")},
            },
        ),
        migrations.CreateModel(
            name="RecommendationHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("movie_id", models.IntegerField(help_text="TMDb movie ID")),
                (
                    "recommendation_type",
                    models.CharField(
                        choices=[
                            ("collaborative", "Collaborative Filtering"),
                            ("content_based", "Content-Based"),
                            ("genre_based", "Genre-Based"),
                            ("popularity", "Popularity-Based"),
                            ("hybrid", "Hybrid"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "confidence_score",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendation_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "recommendation_history",
                "indexes": [
                    models.Index(
                        fields=["user"], name="recommendat_user_id_8946f7_idx"
                    ),
                    models.Index(
                        fields=["movie_id"], name="recommendat_movie_i_aaae53_idx"
                    ),
                    models.Index(
                        fields=["-created_at"], name="recommendat_created_70556f_idx"
                    ),
                    models.Index(
                        fields=["-confidence_score"],
                        name="recommendat_confide_4c9ec5_idx",
                    ),
                ],
            },
        ),
    ]
