# Generated by Django 4.2.7 on 2025-09-28 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserFavorite",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("movie_id", models.IntegerField(help_text="TMDb movie ID")),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movie_favorites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_favorites",
                "indexes": [
                    models.Index(
                        fields=["user"], name="user_favori_user_id_216ac3_idx"
                    ),
                    models.Index(
                        fields=["movie_id"], name="user_favori_movie_i_976f3e_idx"
                    ),
                    models.Index(
                        fields=["-added_at"], name="user_favori_added_a_0f8a90_idx"
                    ),
                ],
                "unique_together": {("user", "movie_id")},
            },
        ),
    ]
